[project]
name = "ser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "audb>=1.11.4",
    "fastparquet>=2025.12.0",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
]
